-- Fixed local game content. IDs stay stable so saved progress remains valid.
-- Re-running this seed adds missing rows without replacing existing rows.
BEGIN;

INSERT OR IGNORE INTO classic_levels (id, tier, title, passage) VALUES
    (1, 1, 'The Workshop Bell', 'At nine, the workshop bell rang across the courtyard. Mira set a box of loose screws beside the old clock and opened her notebook. She wrote down each small repair before touching a tool. By noon, the clock had a steady tick again, and the bell sounded less lonely in the quiet hall.'),
    (2, 1, 'A Library Map', 'The library kept a hand drawn map near its front desk. It showed narrow aisles, reading tables, and a tiny room for local history. Arun followed the map to a shelf he had never noticed. Between two atlases he found a book of simple machines, full of sketches that made each idea easy to test.'),
    (3, 1, 'Rain at the Stop', 'Rain began just as the bus reached the corner. People moved under the small roof and made room for a woman carrying a stack of paper. A child counted the drops sliding down the sign. When the bus arrived, everyone climbed aboard in order, and the driver waited until the last umbrella was folded.'),
    (4, 1, 'The Rooftop Garden', 'On the roof, ten clay pots stood in a neat row. Each held a different herb, with a paper label tied to the rim. Leena checked the soil with one finger before adding water. The mint needed a little more shade, so she moved it beside the wall. By evening, the leaves had lifted toward the cool air.'),
    (5, 1, 'Harbor Lights', 'At dusk, the harbor lamps came on one by one. A fishing boat returned slowly while two friends watched from the stone steps. They could hear ropes tap against the masts and gulls call over the water. The boat reached its place before dark, and a warm light appeared in the window of the little dock office.'),
    (6, 1, 'The Small Museum', 'The town museum had only three rooms, but every object had a story. Near the door stood a wooden radio that once carried news to the whole street. Nia read its label, then listened to a recording of its soft crackle. She left with a question for her grandfather about the songs he had heard when he was young.'),
    (7, 1, 'Morning Market', 'The market opened before sunrise. Sellers arranged baskets of oranges, fresh bread, and bright flowers along the lane. Dev brought a short list so he would not forget the rice. He stopped to help a vendor lift a heavy crate, then chose a small bunch of flowers for the kitchen table. The street was busy by the time he left.'),
    (8, 1, 'A Clear Night', 'The school telescope stood on a tripod in the field. Clouds had covered the sky all week, but tonight the stars were sharp. Sana adjusted the focus until the moon looked clear at the edge. She stepped aside so everyone could take a turn, then drew what she saw in a plain notebook under a small red lamp.'),
    (9, 1, 'The Bicycle Chain', 'A bicycle chain slipped off near the bridge. Omar turned the bike over, checked the gears, and put the chain back with careful hands. He wiped the oil from his fingers and gave the wheel a slow spin. It moved smoothly, so he packed his cloth and continued along the path before the afternoon heat grew strong.'),
    (10, 1, 'When the Lights Went Out', 'The lights went out during the family quiz. For a moment, everyone sat still and listened to the fan slow down. Then Ada found a lantern, and the game continued around the table. Without the television in the next room, they could hear each answer clearly. The power returned just as the final question was read.'),
    (11, 2, 'The Paper Bridge', 'A class built bridges from paper, tape, and string. Most groups made tall arches, but Rafi folded narrow strips into a low frame. He tested it with coins, adding one at a time until the center bent. After lunch, he changed the folds and tried again. The new bridge carried twice as many coins, although it looked almost the same. Rafi wrote the result beside his sketch so the next group could see what had changed.'),
    (12, 2, 'The Missing Recipe', 'Grandma kept her recipes in a blue tin above the stove. One morning, the card for lemon biscuits was missing. Tara searched the kitchen, checked the pantry, and even looked under the table. At last she found the card inside a library book, where Grandma had used it as a bookmark. The two baked together that afternoon. Tara copied the recipe into a fresh notebook and left the old card in its tin, safe from another trip to the library.'),
    (13, 2, 'Signals on the Hill', 'From the hill, the rescue team could see the entire valley. They placed three bright flags beside the trail to mark a safe route. A storm had washed away the usual signs, and hikers might miss the turn near the stream. Kiran checked each flag from the far ridge, then adjusted one that hid behind a tree. Before the team left, they walked the route again and drew its turns on a simple map for the visitor desk.'),
    (14, 2, 'A New Window', 'The art room had a window that faced a plain brick wall. The students asked if they could paint a small scene around its frame. First they drew a garden on paper, then they chose colors that would stay bright in winter. Their teacher measured the space and helped them mark the edges. When the painting was done, the real light made the green leaves glow. Even on cloudy days, the room felt a little more open.'),
    (15, 2, 'The Quiet Platform', 'At the station, Priya noticed a small board beside the timetable. Travelers had pinned notes there: a lost scarf, a found key, and a request for a ride to the village. She added a note about the blue umbrella she had seen on the last train. The next morning, someone had crossed out her note and written, ''Found it, thank you.'' Priya smiled at the answer. A busy platform could still feel like a place where people looked after one another.'),
    (16, 2, 'The Seed Exchange', 'Every spring, neighbors met at the community hall to trade seeds. Each packet carried a name, a planting date, and a short note about sunlight. Isha brought beans from her balcony garden and took home a few sunflower seeds. She planted them in two pots, one near the railing and one beside the door. A month later, the taller plant showed her which spot received more morning light. She wrote that lesson on next year''s packet.'),
    (17, 2, 'Repairing the Kite', 'The kite flew well until a sudden gust tore its paper tail. Manu caught it before it reached the pond and carried it home. He found light cloth, cut a new tail, and tied it with two firm knots. The first test failed because the cloth was too heavy. He shortened it, moved the knot, and tried again in the open field. This time the kite rose smoothly above the trees, and Manu watched the tail follow each turn without a wobble.'),
    (18, 2, 'Notes from the Ferry', 'On the morning ferry, a student counted the birds that followed the boat. She marked each kind in a pocket notebook and noted where it appeared. Near the shore, she saw many small birds; farther out, only two large ones circled overhead. The captain explained that wind and food both changed their routes. By the time the ferry reached the other bank, her page was full of marks and questions for the science club.'),
    (19, 2, 'The Old Projector', 'The school found an old projector in a storage cupboard. Its lamp still worked, but the picture was dim and crooked. Ezra cleaned the lens with a soft cloth while his teacher checked the stand. They moved the screen closer and adjusted the focus one small turn at a time. Soon a sharp map appeared on the wall. The class used it to trace a river from the mountains to the sea, cheering when the projector held steady through the lesson.'),
    (20, 2, 'A Bench for Everyone', 'The park had a long path but only one bench, close to the gate. A group of neighbors planned another rest spot halfway around the lake. They asked walkers where a bench would help most, measured a level patch, and sent their idea to the park office. When the new bench arrived, they planted flowers nearby. An older runner stopped there on opening day and said the extra place to rest made the whole loop feel welcoming.');

COMMIT;
